
export FLASK_CONFIG=development
export FLASK_APP=dream-team/run.py
PUBLISHABLE_KEY=pk_tes6pRNASCoBOKtIshFeQd4XMUh SECRET_KEY=sk_test_BQokikJOvBiI2HlWgH4olfQ2 flask db migrate
PUBLISHABLE_KEY=pk_tes6pRNASCoBOKtIshFeQd4XMUh SECRET_KEY=sk_test_BQokikJOvBiI2HlWgH4olfQ2 flask db upgrade
PUBLISHABLE_KEY=pk_tes6pRNASCoBOKtIshFeQd4XMUh SECRET_KEY=sk_test_BQokikJOvBiI2HlWgH4olfQ2 flask shell
