"""empty message

Revision ID: 096bebb51cee
Revises: 9ae40574ecf4
Create Date: 2018-02-24 20:12:38.628523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096bebb51cee'
down_revision = '9ae40574ecf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
