"""empty message

Revision ID: 3e610d3bc9a8
Revises: a9b27b0e9440
Create Date: 2018-02-26 17:13:03.298357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e610d3bc9a8'
down_revision = 'a9b27b0e9440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guestLists', sa.Column('needs', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guestLists', 'needs')
    # ### end Alembic commands ###
