"""empty message

Revision ID: 4217faaa33c0
Revises: 3e610d3bc9a8
Create Date: 2018-02-26 17:57:12.087508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4217faaa33c0'
down_revision = '3e610d3bc9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guestLists', 'needs')
    op.add_column('users', sa.Column('needs', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'needs')
    op.add_column('guestLists', sa.Column('needs', mysql.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###
