"""empty message

Revision ID: 557b80819dc1
Revises: 800508a75f98
Create Date: 2018-03-14 13:54:18.727078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557b80819dc1'
down_revision = '800508a75f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('events_attended', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'events_attended')
    # ### end Alembic commands ###
