"""empty message

Revision ID: 78f61f9484dd
Revises: 613d006ab2ec
Create Date: 2018-03-27 17:05:04.085518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f61f9484dd'
down_revision = '613d006ab2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('date', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('purpose', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'purpose')
    op.drop_column('payments', 'date')
    # ### end Alembic commands ###
