"""empty message

Revision ID: 7cb92536d91d
Revises: 4217faaa33c0
Create Date: 2018-02-26 19:04:50.613338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb92536d91d'
down_revision = '4217faaa33c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('menus', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'menus')
    # ### end Alembic commands ###
