"""empty message

Revision ID: 800508a75f98
Revises: 7cb92536d91d
Create Date: 2018-03-14 13:38:12.151443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800508a75f98'
down_revision = '7cb92536d91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'date')
    # ### end Alembic commands ###
