"""empty message

Revision ID: 9567f1b42dca
Revises: 3e8ec3577a1a
Create Date: 2018-03-14 15:47:08.480439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9567f1b42dca'
down_revision = '3e8ec3577a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'events_attended')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('events_attended', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
