"""empty message

Revision ID: 9ae40574ecf4
Revises: b6327cda89bf
Create Date: 2018-02-24 19:53:10.952199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae40574ecf4'
down_revision = 'b6327cda89bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('timeD', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'timeD')
    # ### end Alembic commands ###
