"""empty message

Revision ID: 8e9c49b0028a
Revises: f46446f0f62e
Create Date: 2018-03-14 15:06:04.762908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9c49b0028a'
down_revision = 'f46446f0f62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('events_attended', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('is_subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_subscribed')
    op.drop_column('users', 'events_attended')
    # ### end Alembic commands ###
