"""empty message

Revision ID: 9ca6dcf83ab9
Revises: 8e9c49b0028a
Create Date: 2018-03-14 17:25:29.273298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ca6dcf83ab9'
down_revision = '8e9c49b0028a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'events_attended')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('events_attended', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
